shared:
    image: node:6

jobs:
    job1:
        steps:
            - getold: meta get job3
            - metaset: meta set job1 set-by-job1
            - vim: cat /sd/meta/meta.json
            - echo: echo $SD_TOKEN
        requires: [~commit, ~pr]
    job2:
        steps:
            - echo: echo hi
            - metaset: meta set job2 set-by-job2
        requires: [~commit]
    job3:
        steps:
            - metaset: meta set job3 set-by-job3
            - metaget: meta get job1
            - metaget: meta get job2
            - metaget: meta get job3
        requires: [main, job2]
    newPRJob:
        steps:
            - echo: echo bye
        requires: [~pr]
