jobs:
    annotations:
        screwdriver.cd/cpu: HIGH
        screwdriver.cd/memory: HIGH
    test:
        environment:
            USER_SHELL_BIN: bash
        image: node:6
    
        steps:
            - echo: echo $SD_TOKEN
        requires: [~commit, ~pr]
