# new
shared:
    image: node:6

jobs:
    main:
        steps:
            - sleep: sleep 10000
            - stuff: echo hi
        requires: ~commit
    NEWWWWWNEWTESTPR2:
        steps:
            - echo: echo bye
        requires: [~pr, ~commit]
    NEWWWWWNEWTESTPR3:
        steps:
            - echo: echo bye
        requires: [~pr, ~commit]
    NEWWWWWNEWTESTPR4:
        steps:
            - echo: echo bye
        requires: [~pr, ~commit]
