shared:
    image: node:6

jobs:
    main:
        steps:
            - echoPR: echo $SD_PULL_REQUEST
        requires: ~commit
    nextJob:
        steps:
            - echo: echo bye
        requires: ~main
