shared:
    image: node:6

jobs:
    main:
        annotations:
            beta.screwdriver.cd/executor: queue
        steps:
            - metaset: meta set foo_bar 1300010535
            - metaget: meta get foo_bar
        requires: [~commit, ~pr]
    newPRJob:
        steps:
            - echo: echo bye
        requires: [~pr]
