jobs:
    averylongjobnametestingalongjobname:
        image: node:6
        steps:
            - echo: echo $BAZ
            - env: env
            - ls: ls /tmp
            - ls2: ls /sd
        requires: [~pr:staging, ~commit]
        secrets:
            - MYSECRET
        environment:
            HELLO: hello${MYSECRET}
            FOO: BAR
            BAZ: Hello-$FOO
    test:
        image: node:6
        steps:
            - meta: meta set foo bar
        requires: [~commit]
