shared:
    image: node:6

jobs:
    main:
        steps:
            - metaset: meta set foo barrrrr
            - passstep: echo bye
        requires: [~commit, ~pr]
    newPRJob:
        steps:
            - echo: echo bye
        requires: [~pr]
