shared:
    image: node:6

jobs:
    main:
        steps:
            - metaset: meta set foo barrrrr
            - sleep: sleep 1000
        requires: [~commit, ~pr]
    nextJob:
        steps:
            - echo: echo bye
        requires: main
