jobs:
    test:
        annotations:
            screwdriver.cd/cpu: HIGH
            screwdriver.cd/memory: HIGH
        environment:
            USER_SHELL_BIN: bash
        image: node:6
        steps:
            - set: meta set foo bar
            - get: meta get foo
            - echo: echo $SD_TOKEN
            - test: |
                echo hi
                echo bye
                echo world
        requires: [~commit, ~pr]
