shared:
    image: node:6

jobs:
    main:
        annotations:
            beta.screwdriver.cd/executor: k8s
        steps:
            - metaset: meta set foo barrrrr
            - passstep: echo bye
            - sleep: sleep 1000
        requires: [~commit, ~pr]
    newPRJob:
        steps:
            - echo: echo bye
        requires: [~pr]
