shared:
    image: node:6

jobs:
    main:
        steps:
            - metaset: meta set foo barrrrr
            - failstep: doesnotexist
            - passstep: echo bye
        requires: [~commit, ~pr]
    newPRJob:
        steps:
            - echo: echo bye
        requires: [~pr]
    newPRJob2:
        steps:
            - echo2: echo hello
        requires: [~pr]
