shared:
    image: node:6

jobs:
    main:
        annotations:
            beta.screwdriver.cd/executor: queue
        steps:
            - metaset: meta set build_version_1 "1300010535"
            - metaget: meta get build_version_1
        requires: [~commit, ~pr]
    newPRJob:
        steps:
            - echo: echo bye
        requires: [~pr]
