shared:
    image: node:6

jobs:
    job1:
        steps:
            - getold: meta get job3
            - metaset: meta set job1 set-by-job1
            - vim: cat /sd/meta/meta.json
            - echo: echo $SD_TOKEN
            - sleep: sleep 1
        requires: [~commit, ~pr]
    job2:
        steps:
            - metaset: meta set job2 set-by-job2
            - sleep: sleep 3
        requires: [~commit]
    job3:
        steps:
            - metaset: meta set job2 set-by-job3
            - sleep: sleep 4
        requires: [~commit]
    job4:
        steps:
            - metaset: meta set job4 set-by-job4
            - metaget1: meta get job1
            - metaget2: meta get job2
            - metaget3: meta get job3
            - metaget3: meta get job4
        requires: [job1, job2, job3]
