jobs:
    test:
        annotations:
            screwdriver.cd/cpu: HIGH
            screwdriver.cd/memory: HIGH
        environment:
            USER_SHELL_BIN: bash
        image: node:6
        steps:
            - echo: echo $SD_TOKEN
            - sleep: sleep 1000
        requires: [~commit, ~pr]
