# new
shared:
    image: node:6

jobs:
    main:
        steps:
            - sleep: sleep 10000
            - stuff: echo hi
        requires: ~commit
    TESTPR:
        steps:
            - echo: echo bye
        requires: [~pr]
