# new
shared:
    image: node:6

jobs:
    main:
        steps:
            - sleep: sleep 10000
            - stuff: echo hi
        requires: ~commit
    TESTTTTT:
        steps:
            - echo: echo bye
        requires: [~pr, ~commit]
    TESTTTTT222:
        steps:
            - echo: echo bye
        requires: [~pr, ~commit]
    TESTTTTT3333:
        steps:
            - echo: echo bye
        requires: [~pr, ~commit]
